# This workflow is a demo of how to use the Gihub Actions workflow steps for SignPath. For a complete documentation, 
# view https://github.com/SignPath/github-actions

name: build-and-sign
run-name: Demo workflow signing with SignPath
on: 
  push:
  pull_request:
  schedule:
    - cron:  '30 3 * * *' # every day at 3:30am UTC
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build_and_sign:
    runs-on: windows-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build
      run: ./src/Build.ps1

    - name: create SBOM
      run: ./sbom/Create-SBOM.ps1

    - name: package artifacts
      run: Compress-Archive -Path .\_BuildResult-unsigned\DemoExample.msi,.\_BuildResult-unsigned\bom.xml -DestinationPath .\_BuildResult-unsigned.zip -Force

    - name: upload-unsigned-artifact
      uses: actions/upload-artifact@v3
      with:
        name: "demo-application-unsigned" 
        path: "./_BuildResult-unsigned.zip"
        if-no-files-found: error
    
    - name: sign
      uses: SignPath/github-actions/actions/submit-signing-request@v0.1
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '${{ vars.SIGNPATH_ORGANIZATION_ID }}'
        project-slug: 'Demo_Application'
        signing-policy-slug: ${{ github.ref == 'refs/heads/main' && 'release-signing' || 'test-signing' }}
        artifact-configuration-slug: 'v1'
        artifact-name: "demo-application-unsigned"
        signed-artifact-destination-path: "_BuildResult-signed"

    - name: upload-signed-artifact
      uses: actions/upload-artifact@v3
      with:
        name: "demo-application-signed" 
        path: "_BuildResult-signed"
        if-no-files-found: error
