# This workflow is a demo of how to use the Gihub Actions workflow steps for SignPath. For a complete documentation, 
# view https://github.com/SignPath/github-actions

name: sign-with-signpath
run-name: Demo workflow signing with SignPath
on: 
  push:
  pull_request:
  schedule:
    - cron:  '30 3 * * *' # every day at 3:30am UTC

jobs:
  build-and-sign:
    runs-on: windows-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: "echo \"This is a dummy build step that creates build-output/hello-world.exe\""

    - name: upload-unsigned-artifact
      uses: actions/upload-artifact@v3
      with:
        name: "hello-world" 
        path: "./build-output/hello-world.exe"
        if-no-files-found: error
    
    - name: sign
      # TODO: change to v0.1
      uses: SignPath/github-actions/actions/submit-signing-request@main
      with:
        # TODO: can be removed for PROD deployment
        #connector-url: 'https://githubactions.connectors.fqa.test.signpath.io:15021/'
        #connector-url: 'https://brx6b0w8-44353.euw.devtunnels.ms/'
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '${{ vars.SIGNPATH_ORGANIZATION_ID }}'
        project-slug: 'EXE'
        signing-policy-slug: 'test-signing'
        artifact-configuration-slug: 'initial'
        artifact-name: "hello-world"
        signed-artifact-destination-path: "build-output/hello-world-signed.exe"

    - name: upload-signed-artifact
      uses: actions/upload-artifact@v3
      with:
        name: "hello-world-signed" 
        path: "./build-output/hello-world-signed.exe"
        if-no-files-found: error
